### ISSUE TITLE
merging

### ISSUE THREAD

**Issue by moh1122** [onurcelikeng/Horoscoper#1]
Hello
Amazing proj
but how can I merge it with another pod project?

**Comment by esdonmez** [comment]
Hello @moh1122. It's nice to hear that you like our project. 
Can you explain the problem you have? Do you want to add a pod project to Horoscoper? 
If that's the case, you can look here: https://guides.cocoapods.org/using/using-cocoapods
If not, please feel free to share your problem with us.
